<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net9.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/CycoTui.Core/CycoTui.Core.csproj" />

    <ProjectReference Include="../../src/CycoTui.Backend.Unix/CycoTui.Backend.Unix.csproj" />
    <ProjectReference Include="../../src/CycoTui.Backend.Windows/CycoTui.Backend.Windows.csproj" />
  </ItemGroup>
</Project>
